project:
  type: website
  output-dir: docs

website:
  title: "BlitheringIdiolect"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Blog2.html
        text: Blog
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

