project:
  type: website
  output-dir: docs

website:
  title: "BlitheringIdiolect"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: BlitheringIdiolect.github.io/BlitheringIdiolect/Blog2.qmd
        text: Blog
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

