---
title: Education and Professional Development
---

## CELTA

Awarded 2016

## Community College of the Air Force (Distinguished Graduate)

#### Associate of Applied Scientific Analysis Technology\* (actual title needs checking)

COMPLETED August 2022 <br>Awarded November 2023

The CCAF closed without warning and told us they'd be down for 3 to 6 months. I had **just** been submitted for graduation. 14ish very long months later, they finally awarded the stupid thing.

I still haven't received the actual document.

Distinguished Graduate (DG) requirements:

-   90% or higher overall grade
-   No failed progress checks (PCs)
-   Demonstrates Whole Airman Concept

DG is typically awarded to the member of the class with the highest overall grade though this is not required. (If the top performer is a dirtbag, for example, and the runner up volunteered every week, then the runner up is going to get DG.) Not every class has a DG. While I did have the highest overall grade in my class of 7, I just barely eeked by at 90%.

Whole Airman Concept activities:

-   White Rope (Chapel Volunteer)
    -   Board Member Positions held:
        -   Liaison to the 312th TRS (both for Fire and SPINSTRA)
        -   Assistant Chapel Coordinator
-   Red Rope (Student Leader)
-   Red Cross Volunteer
    -   Organized a group of 8 (9?) students from across services to assist the Red Cross in feeding and housing community members affected by tornado damage
-   Completed German CLEP
-   Class project
    -   Text-based RPG based on the SPINSTRA schoolhouse experience written in C++, primarily on a RaspberryPi (4?) using Text Editor

This is what shows up on my transcripts:

- Physical Education/Wellness
- Seismic Analysis
- Seismic Techniques
- Princ of Computer Operation
- Introduction to Electronics
- Satellite Detection Sys
- Principles of AC Circuits
- Principles of DC Circuits
- Electronic Mathematics (yeah, I don't know either)
- Applied Technical Physics
- Basic Electronic Circuits
- Computer System Administrator
- Network System Administration
- Detection Systems
- Satellite Detection Sys (yes, again)
- Applied Technical Physics ("yes, again" again)

## Jefferson Community & Technical College (GPA 4.0)
### Fall 2021
#### ENG 101 - Writing 1
#### MAT 100 - College Algebra Workshop
#### MAT 150 - College Algebra

### Spring 2022
#### HIS 101 - World Civilization 1
#### SOC 101 - Intro to Sociology

### Fall 2022
#### PSY 110 - General Psychology

### Spring 2023
#### CS 115U - Intro to Computer Programming (BCTC)
#### GLY 130 - Dinosaurs and Disasters

## University of Kentucky (GPA 4.0)

### Fall 2022-2023

#### STA 210

#### EES 180

### Spring 2022-2023

#### LIN 221 - Intro to Linguistics

#### GER 352 - German Linguistics

Taught in German.

#### MCL 591 - Old Norse

### Fall 2023-2024

#### MA 110 - Algebra and Trigonometry for Calculus

(It's Pre-Calc.)

#### LIN 300 - Speech Sounds

#### LIN 500 - Phonetics

#### RUS 101 - Introductory Russian

#### ENG 395 - Old English

### Spring 2023-2024

#### LIN 305 - Words and Sentences

Morphology and Syntax

#### LIN 511 - Computational Lingusitics

#### LIN 331 - Language in U.S. Society

#### LIN 200 - How to Create Your Own Language

Linguistics by fire hose. Resulted in Quekaria.

#### MCL 595 - Proto Indo European

#### MCL 591 - Old Norse

#### MCL 591 - Russian Radio

### Summer 2024

#### PHI 120

registered

#### COM 252

registered

### Fall 2024-2025

#### LIN 506 - Sociolinguistics

registered

#### MA 113 - Calculus 1

registered

#### CS 215

registered

#### CHI 101 - Introductory Chinese

registered

## Future Aspirations

#### Hofstra University

##### MA Forensic Linguistics

#### ???

##### PhD. ??? Linguistics

Something "socio-," no doubt.

## CLEP Tests

-   German - level 2 score (equivalent GER 202)
-   English CLEP #1
-   English CLEP #2
-   Principles of Management

## Additional Professional Development

#### Airman Leadership School (ALS)

Distance Learning; completed 20xx

## Work Studies & Internships

### University of Kentucky Phonetics Lab

#### Research Assistant

### Lockheed Martin

## Clubs and Other Extracurriculars

#### Russian Club

#### German Club

## Organizations

#### Linguistic Society of America (LSA)
